// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TASKHIVE.Data;

#nullable disable

namespace TASKHIVE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250220091751_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TASKHIVE.Model.Meeting", b =>
                {
                    b.Property<int>("meetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("meetingId"));

                    b.Property<string>("meetingLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("scheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("meetingId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("TASKHIVE.Model.Project", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectId"));

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("workSpaceId")
                        .HasColumnType("int");

                    b.HasKey("projectId");

                    b.HasIndex("workSpaceId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TASKHIVE.Model.Report", b =>
                {
                    b.Property<int>("reportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reportId"));

                    b.Property<string>("reportContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("reportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("reportId");

                    b.HasIndex("userId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TASKHIVE.Model.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleId"));

                    b.Property<string>("userRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TASKHIVE.Model.TimeLog", b =>
                {
                    b.Property<int>("timeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("timeLogId"));

                    b.Property<int>("hoursWorked")
                        .HasColumnType("int");

                    b.Property<DateTime>("logDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("workId")
                        .HasColumnType("int");

                    b.HasKey("timeLogId");

                    b.HasIndex("userId");

                    b.HasIndex("workId");

                    b.ToTable("TimeLogs");
                });

            modelBuilder.Entity("TASKHIVE.Model.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("meetingId")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("workSpaceId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("meetingId");

                    b.HasIndex("roleId");

                    b.HasIndex("workSpaceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TASKHIVE.Model.Work", b =>
                {
                    b.Property<int>("workId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("workId"));

                    b.Property<int>("categoryStatus")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("duedate")
                        .HasColumnType("datetime2");

                    b.Property<int>("label")
                        .HasColumnType("int");

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<string>("workName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("workPriority")
                        .HasColumnType("int");

                    b.Property<int>("workStatus")
                        .HasColumnType("int");

                    b.HasKey("workId");

                    b.HasIndex("projectId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("TASKHIVE.Model.WorkSpace", b =>
                {
                    b.Property<int>("workSpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("workSpaceId"));

                    b.Property<string>("workSpaceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("workSpaceId");

                    b.ToTable("WorkSpaces");
                });

            modelBuilder.Entity("TASKHIVE.Model.Project", b =>
                {
                    b.HasOne("TASKHIVE.Model.WorkSpace", "WorkSpace")
                        .WithMany("Projects")
                        .HasForeignKey("workSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSpace");
                });

            modelBuilder.Entity("TASKHIVE.Model.Report", b =>
                {
                    b.HasOne("TASKHIVE.Model.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TASKHIVE.Model.TimeLog", b =>
                {
                    b.HasOne("TASKHIVE.Model.User", "User")
                        .WithMany("TimeLogs")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TASKHIVE.Model.Work", "Work")
                        .WithMany("TimeLogs")
                        .HasForeignKey("workId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TASKHIVE.Model.User", b =>
                {
                    b.HasOne("TASKHIVE.Model.Meeting", "meeting")
                        .WithMany("Users")
                        .HasForeignKey("meetingId");

                    b.HasOne("TASKHIVE.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TASKHIVE.Model.WorkSpace", "workSpace")
                        .WithMany("Users")
                        .HasForeignKey("workSpaceId");

                    b.Navigation("Role");

                    b.Navigation("meeting");

                    b.Navigation("workSpace");
                });

            modelBuilder.Entity("TASKHIVE.Model.Work", b =>
                {
                    b.HasOne("TASKHIVE.Model.Project", "Project")
                        .WithMany("Works")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TASKHIVE.Model.Meeting", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TASKHIVE.Model.Project", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("TASKHIVE.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TASKHIVE.Model.User", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("TASKHIVE.Model.Work", b =>
                {
                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("TASKHIVE.Model.WorkSpace", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
